# Generated by Django 2.1.5 on 2019-07-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=70)),
            ],
        ),
    ]
