# Generated by Django 2.1.5 on 2019-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
